import '../styles/globals.css';
import Head from 'next/head';
import type { AppProps } from 'next/app';
import { useEffect, useState } from 'react';
import { getUser } from '../_lib/user';
import { useRouter } from 'next/router';
import { LINK_SIGN_IN, ALLOWED_PAGES } from '../_consts/Links';
import { Backdrop } from '@mui/material';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import Header from '../components/common/Header';
import Container from '@mui/material/Container';

const theme = createTheme({
  typography: {
    h3: {
      fontFamily: ['Noto Serif KR', 'serif'].join(','),
    },
  },
  palette: {
    primary: {
      main: '#3AC184',
      light: '#3ac18426',
      dark: '#003809',
    },
    secondary: {
      main: '#BDDB79',
    },
  },
});

const PageHead = () => (
  <Head>
    <title>{'Aents Standalone Template'}</title>
    <meta name='description' content='Generated by create next app' />
    <link rel='icon' href='/favicon.ico' />
  </Head>
);

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps) {
  const [user, setUser] = useState<any>(null);
  const router = useRouter();

  useEffect(() => {
    if (pageProps.protected) {
      const user = getUser();
      if (user === null) router.push(LINK_SIGN_IN);
      else setUser(user);
    }
  }, [pageProps.protected, router]);

  const FilteredComponent = () => {
    if (ALLOWED_PAGES.includes(router.pathname))
      return <Component {...pageProps} />;
    if (!user) return <Backdrop open />;
    return <Component {...pageProps} />;
  };

  return (
    <>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <PageHead />
        <Container maxWidth='lg' sx={{ height: 'maxContent' }}>
          <Header />
          <FilteredComponent />
        </Container>
      </ThemeProvider>
    </>
  );
}
